### ISSUE TITLE
Auto-generate types from JSON-schema

### ISSUE THREAD

**Issue by KATT** [unit-finance/unit-node-sdk#124]
Hey people!

I just wanted to open up a suggestion. I've noticed a few instances of types being mismatched from the API-docs. Correct me if I'm wrong, but it seems like you're currently manually wiring the types in TypeScript which will inevitably lead to inconsistencies.

Assuming the [JSON Schema linked in the docs](https://docs.unit.co/#json-schema) can be trusted, it would make sense to me if you used a tool for automatically generating all the TypeScript-types based on that rather than manually keeping them up to date.

There are libraries that do this sort of work for you, check out [bcherny/json-schema-to-typescript](https://github.com/bcherny/json-schema-to-typescript) for instance - you can play with the output of it [here](https://transform.tools/json-schema-to-typescript).

Doing this automatically could help prevent issues like #104 / #118 / #122 / #119

**Comment by obando777** [comment]
This idea is fantastic, Yet the [JSON Schema linked in the docs](https://docs.unit.co/#json-schema) will need to be more strict and properly typesafe to be helpful as a source of truth. It is not wrong typed, but it contains instances of ```[k: string]: unknown;```. Some attributes like the tags are expected to hold that open-ended type, but after parsing the schema, it looks like it is all around. Furthermore, not all types/classes are present on the [JSON Schema linked in the docs](https://docs.unit.co/#json-schema); things like webhooks seem to be missed. 

Take a look at just the account type definition. https://codesandbox.io/s/headless-sea-ohk9nv?file=/src/account.ts

I will prefer some manually wired types over unsafe or even missed types. I think the way to go is automatically generating a strict-typed source of truth. I will love to know if there is any plan to support some Swagger or improve the  [JSON Schema linked in the docs](https://docs.unit.co/#json-schema).


I am currently parsing this out using the zip in the docs directly.
```npx tsget-from-json-schema https://docs.unit.co/json-schemas.zip ./types```

**Comment by Yaellever** [comment]
Hey  @KATT @obando777 
Just wanted to update that we have recently started working on OpenAPI support for our JSON schema, but do plan on continuing to manually update our Node SDK. It's work in progress and don't yet have an ETA for this but wanted to thank you guys for the input and let you know we are looking into this.
@axshani

**Comment by obando777** [comment]
If there is something that I can help with about those efforts let me know
i am eager to help you guys with that endeavor
