### ISSUE TITLE
Create debit card request: additional attributes

### ISSUE THREAD

**Issue by ilyamerman** [unit-finance/unit-node-sdk#130]
https://docs.unit.co/cards/#attributes

additionalEmbossedText
digitallyActive
limits

Appears on all 4 creation types (Individual / Business / IndividualVirtual / BusinessVirtual
(maybe can be done as part of https://github.com/unit-finance/unit-node-sdk/pull/110 ?)

**Comment by axshani** [comment]
I've added BaseCreateCardRequestAttributes and I've made the changes as part of #110 as you suggested.
digitallyActive isn't appears on IndividualVirtual, please re-check that for us.
P.S, I saw that there are some wrong attributes to create Individual card and removed them, can you please check that too?

**Comment by axshani** [comment]
I've added BaseCreateCardRequestAttributes and I've made the changes as part of #110 as you suggested.
digitallyActive isn't appears on IndividualVirtual, please re-check that for us.
P.S, I saw that there are some wrong attributes to create Individual card and removed them, can you please check that too?
