### ISSUE TITLE
Installed module import errors

### ISSUE THREAD

**Issue by swwelch** [unit-finance/unit-node-sdk#14]
Hi! Thanks for making this SDK available.

I've installed the package into a Node.js project using yarn:
```
yarn add @unit-finance/unit-node-sdk --save
```
The installed module in `node_modules` has the following error when trying to import:
```js
import { Unit } from '@unit-finance/unit-node-sdk';
```
>Cannot find module '@unit-finance/unit-node-sdk' or its corresponding type declarations.ts(2307)

I've also tried importing as
```js
import { Unit } from '@unit-finance/unit-node-sdk/unit';
```
but that also leads to build errors:
>internal/modules/cjs/loader.js:883
>  throw err;
>  ^
>Error: Cannot find module '@unit-finance/unit-node-sdk/unit'

It looks like `package.json` [has `index.js` as "main" ](https://github.com/unit-finance/unit-node-sdk/blob/main/package.json#L5) instead of `unit.ts`, but I also don't see `module.exports` in the `unit.ts` file.

**Comment by Elroie** [comment]
Hi @swwelch thanks for the issue,
I've pushed a fix for the importing problem.
Please visit the README again as some changes may be required.
