### ISSUE TITLE
Customer response types are incorrect

### ISSUE THREAD

**Issue by trevoro** [unit-finance/unit-node-sdk#151]
When retrieving a customer using the unit-node-sdk, the response does not include the proper type.
In order for the type to be set properly the developer has to switch on the `response.data.type` then assert it as one of the types exported from the library.

https://github.com/unit-finance/unit-node-sdk/blob/main/types/customer.ts

We're using unit-node-sdk 0.9.17

**Comment by ilyamerman** [comment]
Hi @trevoro,

Just making sure we understand the issue correctly:
The response of a [customers get endpoint](https://github.com/unit-finance/unit-node-sdk/blob/460cee153be0eb73b3d47ec126ac39aa7aab1ff4/resources/customer.ts#L15-L17) returns a response with a type `Customer` which is one of `IndividualCustomer` or `BusinessCustomer`, but you're looking for a static way to know which one of them (Individual / Business) actually returns?

Unit's [customers get endpoint](https://docs.unit.co/customers#get-specific-customer) will always return some kind of a customer which can be identified by the `type` field, this isn't specific to this SDK, any other implementation will have to do it somehow unless Unit implements a `getIndividual` or `getBusiness` endpoints.

Just wondering if we understad correctly + also wondering why is another assertion / casting needed in your case?
<img width="409" alt="image" src="https://user-images.githubusercontent.com/18516271/163169343-b1a67251-3ee6-4f03-b519-33dcebb4b554.png">
