### ISSUE TITLE
Add support for missing webhook events types

### ISSUE THREAD

**Issue by pklicnik** [unit-finance/unit-node-sdk#178]
The following types are missing from the webhook events definitions in https://github.com/unit-finance/unit-node-sdk/blob/main/types/events.ts

```
"authorization.canceled"
"authorization.amountChanged"
"authorization.declined"
"dispute.created"
"dispute.statusChanged"
"checkDeposit.created"
"checkDeposit.pendingReview"
"checkDeposit.pending"
"checkDeposit.rejected"
"checkDeposit.clearing"
"checkDeposit.sent"
"checkDeposit.returned"
"bulkPayments.failed"
"bulkPayments.finished"
"payment.rejected"
"payment.canceled"
"payment.pendingReview"
"declinedIncomingPayment.created"
```

Would like these added so we can continue to use the generic `UnitEvent` type without having to provide a custom definition

**Comment by axshani** [comment]
Merged on https://github.com/unit-finance/unit-node-sdk/releases/tag/0.9.31
