### ISSUE TITLE
Add support for international addresses in the createAddress helper

### ISSUE THREAD

**Issue by pklicnik** [unit-finance/unit-node-sdk#180]
The `state` parameter is hardcoded to the `State` type, which only lists US states:
https://github.com/unit-finance/unit-node-sdk/blob/main/helpers.ts#L2

We can't use this function for international addresses because of this typing.

Would be nice to remove that explicit `State` typing (or, alternatively, another function to support international addresses) so this function can be used for international addresses as well

**Comment by axshani** [comment]
Merged on https://github.com/unit-finance/unit-node-sdk/releases/tag/0.9.31
