### ISSUE TITLE
Complete CardLimits object is required to create debit card

### ISSUE THREAD

**Issue by pklicnik** [unit-finance/unit-node-sdk#181]
If card limits are supplied during card creation, the complete `CardLimits` object is required.
https://github.com/unit-finance/unit-node-sdk/blob/main/types/cards.ts#L249
https://github.com/unit-finance/unit-node-sdk/blob/493d610786bddcc95489052fead4697702e6138e/types/cards.ts#L413

The `dailyTotals` and `monthlyTotals` are required to be provided as part of the typings, but are are not required by the API(and are read-only using the `/cards/:cardId/limits` API, as far as I can tell). They should be removed from the typings

**Comment by ilyamerman** [comment]
https://github.com/unit-finance/unit-node-sdk/releases/tag/0.9.31
