### ISSUE TITLE
Get list of authorization returns "Invalid Json" 

### ISSUE THREAD

**Issue by roperjojodomingo** [unit-finance/unit-node-sdk#183]
This shouldn't be an array based on https://docs.unit.co/cards-authorizations/#list-authorizations
https://github.com/unit-finance/unit-node-sdk/blob/493d610786bddcc95489052fead4697702e6138e/resources/authorization.ts#L92

**Comment by ilyamerman** [comment]
Hi @roperjojodomingo, thank you for reporting
This has been fixed on https://github.com/unit-finance/unit-node-sdk/releases/tag/0.9.30
