### ISSUE TITLE
Field `status` and others are missing on the `Authorization` type

### ISSUE THREAD

**Issue by phillip-kravtsov** [unit-finance/unit-node-sdk#191]
https://github.com/unit-finance/unit-node-sdk/blob/main/types/authorization.ts
https://docs.unit.co/resources#authorization

status, decline reason, transaction-related attributes appear to be missing

**Comment by axshani** [comment]
You are right, I saw this last week and it's already part of this pr: https://github.com/unit-finance/unit-node-sdk/pull/190

**Comment by ilyamerman** [comment]
Merged on https://github.com/unit-finance/unit-node-sdk/releases/tag/0.9.31
