### ISSUE TITLE
AuthorizationDeclined event type is incorrect.

### ISSUE THREAD

**Issue by chrisrodz** [unit-finance/unit-node-sdk#192]
Looks like the `AuthorizationDeclined` event definition is incorrect. The `attributes` field is extending `AuthorizationRelationships` where it should be extending `AuthorizationAttributes`

Here is the type definition in the latest SDK version: https://github.com/unit-finance/unit-node-sdk/blob/9ad1fa9bfb6b1bd22d3a415145827f5c3026aca2/types/events.ts#L102-L108

Let me know if the correct process for this would be to raise a PR to fix it.

Thanks in advance.

**Comment by ilyamerman** [comment]
Fixed on https://github.com/unit-finance/unit-node-sdk/releases/tag/0.9.32
Thanks!
