### ISSUE TITLE
Missing Pagination Parameters in list params for transactions and payments resources

### ISSUE THREAD

**Issue by Physicliar** [unit-finance/unit-node-sdk#245]
https://github.com/unit-finance/unit-node-sdk/blob/4bfc4ceaae319bf5cf8f9099cd0549761384662b/resources/transactions.ts#L81

https://github.com/unit-finance/unit-node-sdk/blob/4bfc4ceaae319bf5cf8f9099cd0549761384662b/resources/payments.ts#L69

In the payment list params and transactions list params the pagination fields are missing. It is also possible that there are more missing fields. Can you please fields so the sdk will have better capabilities.

**Comment by ilyamerman** [comment]
Hey @Physicliar, are you referring to "limit" and "offset"?
They to exist on `BaseListParams` so the attributes are available
`unit.transactions.list({limit: 100, offset: 50})` works
