### ISSUE TITLE
Issue Closing an Account

### ISSUE THREAD

**Issue by edisongiraldo** [unit-finance/unit-node-sdk#267]
I'm using the method `unitCoClient.accounts.closeAccount()` in order to close an Account.
The request object looks like this:
```js
{
  accountId: '',
  reason: '',
}
```

I'm getting an error message: _request.to_json is not a function_

Any thoughts about what could be causing this issue?

Thanks in advance.

**Comment by ilyamerman** [comment]
Hi @edisongiraldo ,
This was a mistake and the code has been fixed on version 0.9.60
We also added a test to instruct on how to use the close function https://github.com/unit-finance/unit-node-sdk/blob/main/tests/accounts.spec.ts#L74-L84

Thank you for reporting
