### ISSUE TITLE
Read scopes missing from UnitScope

### ISSUE THREAD

**Issue by alexlukelevy** [unit-finance/unit-node-sdk#269]
`UnitScope` only includes write scopes at the moment, causing a compilation error if you try and set read scopes (e.g. `'accounts'`)

**Comment by ilyamerman** [comment]
Added on https://github.com/unit-finance/unit-node-sdk/releases/tag/0.9.61
Also, question: we're not currently using the scopes anywhere in our code, can we ask what this is used for on your end?

**Comment by alexlukelevy** [comment]
> Added on https://github.com/unit-finance/unit-node-sdk/releases/tag/0.9.61 Also, question: we're not currently using the scopes anywhere in our code, can we ask what this is used for on your end?

Thanks for that.

I wanted to type the `scopes` required in `unit.customerToken.createToken()`. I build up the `scopes` string from an array of `UnitScope`s.
