### ISSUE TITLE
Error type definition is different in code and docs

### ISSUE THREAD

**Issue by LucasLemanowicz** [unit-finance/unit-node-sdk#270]
Code (https://github.com/unit-finance/unit-node-sdk/blob/df0a08b/types/common.ts#L453-L461):
```typescript
// https://docs.unit.co/#intro-errors
export interface UnitErrorPayload {
    status: string // http status code
    title: string
    code?: string
    details?: string
    source?: { pointer: string; }
    [k: string]: unknown // allow for other keys
}
```

Docs (https://docs.unit.co/about-jsonapi/#intro-errors):

> An "error object" MUST contain a title and the HTTP status code members with one or more of the following:
> 
> code: a Unit-specific code, uniquely identifying the error type.
> detail: additional information about the error.
> meta.supportId unique error identifier to be used for further investigation

```json
{
    "errors": [
        {
            "title": "Not Found",
            "status": "404",
            "detail": "The specified card with id 10001 was not found",
            "meta": {
                "supportId": "a9d774af-972a-47bd-bd3c-9bd79a21f35a"
            }
        }
    ]
}
```

Feedback:
1. Is it `detail` or `details`?
2. If `meta.supportId` is common enough to be called out in the docs, should it also be added as an optional field to UnitErrorPayload?

**Comment by deriegle** [comment]
I've had this same problem. The API actually returns `detail` in the response, so `details` is always undefined.

**Comment by ilyamerman** [comment]
1. The correct one is "details", but due to an inconsistency in our API it is sometimes still only "detail". This will be fixed in the near future and will be part of a list of breaking changes, but for now we are going to support both attribute names, apologies.
2. It is common enough, added :)
