### ISSUE TITLE
Get application response is not correctly typed

### ISSUE THREAD

**Issue by NaimSakaamini** [unit-finance/unit-node-sdk#274]
`get(applicationId: string): Promise<UnitResponse<Application> & Include<ApplicationDocument[]>>`

The actual response is : 
```
included: [ {type:"document", ...}, {type:"beneficialOwner", ...} ]
```
We're missing an optional [beneficial owner resource](https://docs.unit.co/resources#beneficialowner) in the included data.

Thank you 🙇‍♂️

**Comment by ilyamerman** [comment]
Fixed on https://github.com/unit-finance/unit-node-sdk/releases/tag/0.9.61
