### ISSUE TITLE
PatchIndividualCustomerRequest missing jwtSubject property

### ISSUE THREAD

**Issue by alexlukelevy** [unit-finance/unit-node-sdk#287]
The patch customer types are missing the `jwtSubject` property found in the [API](https://docs.unit.co/customers#attributes).

**Comment by alexlukelevy** [comment]
I've subsequently noticed that `AuthorizedUser` is also missing `jwtSubject`.

**Comment by warent** [comment]
ApplicationFormPrefill is also missing this property
