### ISSUE TITLE
Country Codes seem to not support US

### ISSUE THREAD

**Issue by 16dprice** [unit-finance/unit-node-sdk#289]
When trying to create a customer token verification, I get a Unit error because of the phone number. The response gives a `UnitError` where one of the issues is that I sent a `1` for a country code. The API responds that this is not a valid country code and provides the following regex that is apparently used for validating country codes:
```
'^(93|358|355|213|684|376|244|1264|672|1268|54|374|297|61|43|994|1242|973|880|1246|375|32|501|229|1441|975|591|599|387|267|55|55|246|673|359|226|257|855|237|238|1345|236|235|56|86|61|61|57|269|242|242|682|506|225|385|53|599|357|420|45|253|1767|1849|593|20|503|240|291|372|251|500|298|679|358|33|594|689|241|220|995|49|233|350|30|299|1473|590|1671|502|44|224|245|592|509|379|504|852|36|354|91|62|98|964|353|44|972|39|1876|81|44|962|77|254|686|82|850|383|965|996|856|371|961|266|231|218|423|370|352|853|389|261|265|60|960|223|356|692|596|222|230|262|52|691|373|377|976|382|1664|212|258|95|264|674|977|31|687|64|505|227|234|683|672|1670|47|968|92|680|970|507|675|595|51|63|872|48|351|1939|974|262|40|7|250|590|290|1869|1758|599|508|1784|685|378|239|966|221|381|248|232|65|599|421|386|677|252|27|500|211|34|94|249|597|47|268|46|41|963|886|992|255|66|670|228|690|676|1868|216|90|993|1649|688|256|380|971|44|246|598|998|678|58|84|1284|1340|681|212|967|260|263)$'
```

I understand that this is not actually checked anywhere in the SDK, but it seems to be a Unit backend error, which is why I post it here.

For some extra context, here's a code snippet that causes this error:

```
export const createCustomerTokenVerification = async (customerId: number, phone: string): Promise<VerificationToken> => {
  const unit = buildUnitSDKObject();

  const createTokenVerificationRequest: CreateTokenVerificationRequest = {
    type: "customerTokenVerification",
    attributes: {
      channel: "sms",
      phone: {
        countryCode: "1",
        number: phone,
      },
    },
  };

  const tokenVerification = await unit.customerToken.createTokenVerification(
    `${customerId}`,
    createTokenVerificationRequest,
  );

  return getUnitResourceFromResponse(tokenVerification);
};
```

where `buildUnitSDKObject` and `getUnitResourceFromResponse` are custom in-house functions.

**Comment by 16dprice** [comment]
Notably, I think this _might_ be due to the `phone` argument being an incorrect format. For some reason, Unit returns that the country code is also wrong. I have not verified this, but will post in this thread once I have.

**Comment by ilyamerman** [comment]
@16dprice the validation error does look misleading and we will look into it, but country code "1" is supported. 
The "phone" field expects a string of 10 digits describing the phone (https://docs.unit.co/types/#phone) can you please validate that it is indeed the length of your "phone"?

**Comment by Yaellever** [comment]
Since this is a validation issue I'm closing this and creating a bug report for Unit. 
Thanks!
