### ISSUE TITLE
Cancel Application endpoint is missing

### ISSUE THREAD

**Issue by ianm-zen** [unit-finance/unit-node-sdk#304]
The following API endpoint is missing from the node SDK.  I would expect this to be available so we can cancel an in-progress application from the User.

https://docs.unit.co/applications#cancel-application

[Here](https://github.com/unit-finance/unit-node-sdk/blob/main/resources/application.ts) would be where I would hope to see it.  For now, we are making a direct call to Axios.

**Comment by ilyamerman** [comment]
Merged on 0.13.0
