### ISSUE TITLE
transactionSummaryOverride on book payment should be optional, not required

### ISSUE THREAD

**Issue by GuiSim** [unit-finance/unit-node-sdk#324]
The [create book payment](https://docs.unit.co/book-payments/#book-payments) call allows you to pass an optional `transactionSummaryOverride`.

However the `BookPayment` interface defines this field as a `string` in TypeScript, making it non-optional.

see https://github.com/unit-finance/unit-node-sdk/blob/8b580b788f9e531d53a80a752906ee1a38a36189/types/payments.ts#L147-L150

**Comment by ilyamerman** [comment]
Fixed on 0.14.0, thank you!
