### ISSUE TITLE
Split types `NumberOfEmployees` / `AnnualRevenue` between a sole proprietor 

### ISSUE THREAD

**Issue by KATT** [unit-finance/unit-node-sdk#336]
`NumberOfEmployees` / `AnnualRevenue` would be nice to have split between the different types of applications

- https://docs.unit.co/types/#annual-revenue
- https://docs.unit.co/types/#number-of-employees
- https://github.com/unit-finance/unit-node-sdk/blob/ff2cd95aa85a43817fb43a4a24a51c29fb7e387d/types/application.ts#L475-L477

And then, `BaseBusinessApplicationAttributes` could use e.g. `BusinessApplicationNumberOfEmployees` instead of `NumberOfEmployees` here: https://github.com/unit-finance/unit-node-sdk/blob/ff2cd95aa85a43817fb43a4a24a51c29fb7e387d/types/application.ts#L379-L387

**Comment by axshani** [comment]
thanks for the comment!
