### ISSUE TITLE
Missing dba attribute on IndividualCustomer type

### ISSUE THREAD

**Issue by lavoieaj** [unit-finance/unit-node-sdk#390]
`dba` ("doing business as") is an optional attribute on `IndividualCustomer` that can be carried over from sole proprietor applications or added via [Update Individual Customer](https://docs.unit.co/customers#update-individual-customer). It comes through on the customer GET API call but does not appear to be defined in the [resource doc](https://docs.unit.co/resources#individualcustomer) or on the SDK.

**Comment by axshani** [comment]
hey, thanks for this issue
https://github.com/unit-finance/unit-node-sdk/pull/399
