### ISSUE TITLE
Check Payment Counterparty Broken Link

### ISSUE THREAD

**Issue by jtanya17** [unit-finance/unit-node-sdk#403]
According to the docs, https://github.com/unit-finance/unit-node-sdk/blob/main/resources/checkPayments.ts CreateCheckPaymentRequest is linked to the incorrect Counterparty. It should, in fact, reference the CheckPaymentCounterparty within the *.d.ts file

**Comment by jtanya17** [comment]
checkPayments.create() is accepting the type Counterparty, which appears to be the one for ACH payments. So our internal method for issuing a check is getting a type error. Going by what’s in types/common.ts, I think the correct type for this should be checkPaymentCounterparty, not Counterparty. Also, the checkCounterparty type is Pick<Counterparty>, which is a subset of the fields in that same ACH payment type.

**Comment by ilyamerman** [comment]
https://github.com/unit-finance/unit-node-sdk/releases/tag/0.36.1
