### ISSUE TITLE
ATM Locations wrong configurations

### ISSUE THREAD

**Issue by Physicliar** [unit-finance/unit-node-sdk#435]
According to the documentation coordinates param should be a json but in the following it just creates a inner param for each.

Can you please fix this according to the documentation

Expected `/atm-locations?filter[coordinates]={"longitude": "-73.93041", "latitude": "42.79894"}`
Actual Behavior `/atm-locations?filter[coordinates][longitude]=-122.406417&filter[coordinates][latitude]=37.785834`

https://github.com/unit-finance/unit-node-sdk/blob/cc00eeaa5ba0256316f92cf825a3f9821bcad300/resources/atmLocations.ts#L13

**Comment by lucasgruenwald** [comment]
@Yaellever
