### ISSUE TITLE
Type value mismatch for Dishonored ACH transactions

### ISSUE THREAD

**Issue by blueskymonster** [unit-finance/unit-node-sdk#97]
The `type` field of a dishonored ach transaction seems to have the wrong value in the SDK.

According to [the documentation](https://docs.unit.co/resources/#transaction-dishonoredach) it should be `dishonoredAchTransaction`.

But [in the SDK](https://github.com/unit-finance/unit-node-sdk/blob/bde55c73695e7a286bea1673a982bc3411ad7d49/types/transactions.ts#L235), it's expressed as `dishonoredReceivedAchTransaction`. This seems like a typo / copy-paste issue.

**Comment by JVMartin** [comment]
It appears that this SDK is not typesafe, it doesn't use anything like [io-ts](https://github.com/gcanti/io-ts) or [class-validator](https://github.com/typestack/class-validator) to do runtime type identification on the JSON that is being returned from the server requests, so there's no guarantee the types are safe...

**Comment by axshani** [comment]
thanks. https://github.com/unit-finance/unit-node-sdk/pull/108
